@DistanceCalculator.API_HostAddress = http://localhost:5223

### Calculate Distance using Spherical Method (Irish locale)
POST {{DistanceCalculator.API_HostAddress}}/calculate/spherical
Content-Type: application/json

{
  "locale": "en-IE",
  "coordinates": [
    {
      "latitude": 53.297975,
      "longitude": -6.372663
    },
    {
      "latitude": 41.385101,
      "longitude": -81.440440
    }
  ]
}

###

### Calculate Distance using Haversine Method (Irish locale)
POST {{DistanceCalculator.API_HostAddress}}/calculate/haversine
Content-Type: application/json

{
  "locale": "en-IE",
  "coordinates": [
    {
      "latitude": 53.297975,
      "longitude": -6.372663
    },
    {
      "latitude": 41.385101,
      "longitude": -81.440440
    }
  ]
}

###

### Calculate Distance using Pythagorean Method (Irish locale)
POST {{DistanceCalculator.API_HostAddress}}/calculate/pythagorean
Content-Type: application/json

{
  "locale": "en-IE",
  "coordinates": [
    {
      "latitude": 53.297975,
      "longitude": -6.372663
    },
    {
      "latitude": 41.385101,
      "longitude": -81.440440
    }
  ]
}

###

### Calculate Distance using Spherical Method (UK locale)
POST {{DistanceCalculator.API_HostAddress}}/calculate/spherical
Content-Type: application/json

{
  "locale": "en-GB",
  "coordinates": [
    {
      "latitude": 53.297975,
      "longitude": -6.372663
    },
    {
      "latitude": 41.385101,
      "longitude": -81.440440
    }
  ]
}

###

### Calculate Distance using Haversine Method (UK locale)
POST {{DistanceCalculator.API_HostAddress}}/calculate/haversine
Content-Type: application/json

{
  "locale": "en-GB",
  "coordinates": [
    {
      "latitude": 53.297975,
      "longitude": -6.372663
    },
    {
      "latitude": 41.385101,
      "longitude": -81.440440
    }
  ]
}

###

### Calculate Distance using Pythagorean Method (Irish locale)
POST {{DistanceCalculator.API_HostAddress}}/calculate/pythagorean
Content-Type: application/json

{
  "locale": "en-GB",
  "coordinates": [
    {
      "latitude": 53.297975,
      "longitude": -6.372663
    },
    {
      "latitude": 41.385101,
      "longitude": -81.440440
    }
  ]
}

###

### Calculate Distance using Spherical Method (US locale)
POST {{DistanceCalculator.API_HostAddress}}/calculate/spherical
Content-Type: application/json

{
  "locale": "en-US",
  "coordinates": [
    {
      "latitude": 53.297975,
      "longitude": -6.372663
    },
    {
      "latitude": 41.385101,
      "longitude": -81.440440
    }
  ]
}

###

### Calculate Distance using Haversine Method (US locale)
POST {{DistanceCalculator.API_HostAddress}}/calculate/haversine
Content-Type: application/json

{
  "locale": "en-US",
  "coordinates": [
    {
      "latitude": 53.297975,
      "longitude": -6.372663
    },
    {
      "latitude": 41.385101,
      "longitude": -81.440440
    }
  ]
}

###

### Calculate Distance using Pythagorean Method (US locale)
POST {{DistanceCalculator.API_HostAddress}}/calculate/pythagorean
Content-Type: application/json

{
  "locale": "en-US",
  "coordinates": [
    {
      "latitude": 53.297975,
      "longitude": -6.372663
    },
    {
      "latitude": 41.385101,
      "longitude": -81.440440
    }
  ]
}

###
